{"uuid": "17bbb3e6-8f6c-4bd9-905b-e61ab7906b03", "children": ["d4ae8a0b-52d4-4d80-9521-a3f9f696fee4"], "befores": [{"name": "_xunit_setup_method_fixture_TestLogin", "status": "broken", "statusDetails": {"message": "selenium.common.exceptions.WebDriverException: Message: An unknown server-side error occurred while processing the command. Original error: 'POST /element' cannot be proxied to UiAutomator2 server because the instrumentation process is not running (probably crashed). Check the server log and/or the logcat output for more details\nStacktrace:\nUnknownError: An unknown server-side error occurred while processing the command. Original error: 'POST /element' cannot be proxied to UiAutomator2 server because the instrumentation process is not running (probably crashed). Check the server log and/or the logcat output for more details\n    at UIA2Proxy.command (C:\\Program Files\\Appium Server GUI\\resources\\app\\node_modules\\appium\\node_modules\\appium-base-driver\\lib\\jsonwp-proxy\\proxy.js:274:13)\n    at runMicrotasks (<anonymous>)\n    at processTicksAndRejections (internal/process/task_queues.js:97:5)\n    at AndroidUiautomator2Driver.helpers.doFindElementOrEls (C:\\Program Files\\Appium Server GUI\\resources\\app\\node_modules\\appium\\node_modules\\appium-uiautomator2-driver\\lib\\commands\\find.js:32:12)\n    at doFind (C:\\Program Files\\Appium Server GUI\\resources\\app\\node_modules\\appium\\node_modules\\appium-android-driver\\lib\\commands\\find.js:36:17)\n    at wrappedCondFn (C:\\Program Files\\Appium Server GUI\\resources\\app\\node_modules\\appium\\node_modules\\appium-base-driver\\lib\\basedriver\\commands\\timeout.js:151:12)\n    at spin (C:\\Program Files\\Appium Server GUI\\resources\\app\\node_modules\\appium\\node_modules\\asyncbox\\lib\\asyncbox.js:138:20)\n    at waitForCondition (C:\\Program Files\\Appium Server GUI\\resources\\app\\node_modules\\appium\\node_modules\\asyncbox\\lib\\asyncbox.js:155:10)\n    at AndroidUiautomator2Driver.implicitWaitForCondition (C:\\Program Files\\Appium Server GUI\\resources\\app\\node_modules\\appium\\node_modules\\appium-base-driver\\lib\\basedriver\\commands\\timeout.js:153:10)\n    at AndroidUiautomator2Driver.findElOrEls (C:\\Program Files\\Appium Server GUI\\resources\\app\\node_modules\\appium\\node_modules\\appium-android-driver\\lib\\commands\\find.js:60:5)\n    at AndroidUiautomator2Driver.findElOrElsWithProcessing (C:\\Program Files\\Appium Server GUI\\resources\\app\\node_modules\\appium\\node_modules\\appium-base-driver\\lib\\basedriver\\commands\\find.js:33:12)\n    at AndroidUiautomator2Driver.findElement (C:\\Program Files\\Appium Server GUI\\resources\\app\\node_modules\\appium\\node_modules\\appium-base-driver\\lib\\basedriver\\commands\\find.js:53:10)\n", "trace": "  File \"c:\\users\\27632\\pycharmprojects\\pythonproject\\venv\\lib\\site-packages\\pluggy\\_callers.py\", line 39, in _multicall\n    res = hook_impl.function(*args)\n  File \"c:\\users\\27632\\pycharmprojects\\pythonproject\\venv\\lib\\site-packages\\_pytest\\fixtures.py\", line 1130, in pytest_fixture_setup\n    result = call_fixture_func(fixturefunc, request, kwargs)\n  File \"c:\\users\\27632\\pycharmprojects\\pythonproject\\venv\\lib\\site-packages\\_pytest\\fixtures.py\", line 902, in call_fixture_func\n    fixture_result = next(generator)\n  File \"c:\\users\\27632\\pycharmprojects\\pythonproject\\venv\\lib\\site-packages\\_pytest\\python.py\", line 907, in xunit_setup_method_fixture\n    _call_with_optional_argument(func, method)\n  File \"c:\\users\\27632\\pycharmprojects\\pythonproject\\venv\\lib\\site-packages\\_pytest\\python.py\", line 787, in _call_with_optional_argument\n    func()\n  File \"C:\\Users\\27632\\PycharmProjects\\Practice_Allure\\scripts_all\\test_login.py\", line 16, in setup\n    self.login_page = LoginPage(self.driver)\n  File \"C:\\Users\\27632\\PycharmProjects\\Practice_Allure\\page\\login_page.py\", line 21, in __init__\n    self.click(self.agree_continue_button)\n  File \"C:\\Users\\27632\\PycharmProjects\\Practice_Allure\\base\\base_action.py\", line 26, in click\n    self.find_element(loc).click()\n  File \"C:\\Users\\27632\\PycharmProjects\\Practice_Allure\\base\\base_action.py\", line 15, in find_element\n    return WebDriverWait(self.driver, time, poll).until(lambda x: x.find_element(by, value))\n  File \"c:\\users\\27632\\pycharmprojects\\pythonproject\\venv\\lib\\site-packages\\selenium\\webdriver\\support\\wait.py\", line 86, in until\n    value = method(self._driver)\n  File \"C:\\Users\\27632\\PycharmProjects\\Practice_Allure\\base\\base_action.py\", line 15, in <lambda>\n    return WebDriverWait(self.driver, time, poll).until(lambda x: x.find_element(by, value))\n  File \"c:\\users\\27632\\pycharmprojects\\pythonproject\\venv\\lib\\site-packages\\appium\\webdriver\\webdriver.py\", line 383, in find_element\n    return self.execute(RemoteCommand.FIND_ELEMENT, {'using': by, 'value': value})['value']\n  File \"c:\\users\\27632\\pycharmprojects\\pythonproject\\venv\\lib\\site-packages\\selenium\\webdriver\\remote\\webdriver.py\", line 440, in execute\n    self.error_handler.check_response(response)\n  File \"c:\\users\\27632\\pycharmprojects\\pythonproject\\venv\\lib\\site-packages\\appium\\webdriver\\errorhandler.py\", line 30, in check_response\n    raise wde\n  File \"c:\\users\\27632\\pycharmprojects\\pythonproject\\venv\\lib\\site-packages\\appium\\webdriver\\errorhandler.py\", line 26, in check_response\n    super().check_response(response)\n  File \"c:\\users\\27632\\pycharmprojects\\pythonproject\\venv\\lib\\site-packages\\selenium\\webdriver\\remote\\errorhandler.py\", line 245, in check_response\n    raise exception_class(message, screen, stacktrace)\n"}, "start": 1686128680999, "stop": 1686128700674}], "start": 1686128680999, "stop": 1686128700722}